# Generated by Django 3.1.1 on 2020-09-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.IntegerField()),
                ('depto', models.CharField(help_text='Por Ej PBK o 2A', max_length=10)),
                ('nro_medidor', models.CharField(help_text='Numero completo de Medidor', max_length=15)),
                ('propietario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mediciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_medidor', models.IntegerField()),
                ('mes_medicion', models.DateTimeField(blank=True, null=True)),
                ('unidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.unidades')),
            ],
        ),
    ]
